# -*- coding: utf-8 -*-
"""SIRDailyCases.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NYQlhnx1eSszgXoLW6vmPf1_BQrNW-Ll

# Preprocessing the Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy.lib.arraysetops import setxor1d
from scipy.integrate import odeint

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Math 142 Project/Datasets1/allData.csv', index_col='DateSpecCollect', parse_dates=True)
df_recovered = pd.read_csv('/content/drive/MyDrive/Math 142 Project/Datasets1/Recovered.csv', index_col='DateSpecCollect', parse_dates=True)

def cumulative_list(name, reference, table):
  size = table.shape[0]
  columns = list(table.columns)
  col_ind = columns.index(reference)
  arr = []
  for i in range(size):
    toAdd = table.iloc[0:i+1, col_ind].sum() + 0.0
    arr.append(toAdd)
  table[name] = arr
  return table

df_temp = df.sort_values(by='DateSpecCollect')
df_temp.drop(columns=['Total.1', '528641'], axis=1, inplace=True)
df_temp.rename(columns={'Total': 'Infected per day'}, inplace=True)
df_temp['Infected per day'] = df_temp['Infected per day'].astype('float64')
df_temp['7-day Avg'] = df_temp['Infected per day'].rolling(window=7).mean()
df_temp['28-day Avg'] = df_temp['Infected per day'].rolling(window=28).mean()
cumulative_list("Cumul. Infected for 7-day Avg", "7-day Avg", df_temp)
cumulative_list("Cumul. Infected for 28-day Avg", "28-day Avg", df_temp)
cumulative_list("Cumul. Infected", "Infected per day", df_temp)
df_temp['Recovered'] = df_recovered

list_recovered = []
for i in range(df.shape[0]):
  to_append = df_temp['Cumul. Infected'][i] - df_temp['Recovered'][i]
  list_recovered.append(to_append)
df_temp['Number of Infected'] = list_recovered

df_new = df_temp.loc['2020-03-15':'2022-02-08', :].copy()
df_new

df_new.to_csv('/content/drive/MyDrive/UCI Conference/Dataset1/allData1.csv')

df_wave1 = df_new.loc['2020-04-01':'2020-09-30', :].copy()
df_wave2 = df_new.loc['2020-10-01': '2021-03-31', :].copy()
df_wave3 = df_new.loc['2021-07-01': '2021-10-31', :].copy()

df_wave1.to_csv('/content/drive/MyDrive/UCI Conference/Dataset1/wave1Averaged_Nameer.csv')
df_wave2.to_csv('/content/drive/MyDrive/UCI Conference/Dataset1/wave2Averaged_Nameer.csv')
df_wave3.to_csv('/content/drive/MyDrive/UCI Conference/Dataset1/wave3Averaged_Nameer.csv')

"""# Plotting the Data"""

def odes(x, t, a_param, k_param):
  #constants
  # a = 1/infection_rate
  # k = 1/infectious_period
  a = a_param
  k = k_param

  #assign each ODE to a vector element
  S = x[0]
  I = x[1]
  R = x[2]

  #define each ODE
  dSdt = -a*S*I
  dIdt = a*S*I - k*I
  dRdt = k*I

  return [dSdt, dIdt, dRdt]

test_a = 1/2.5
test_k = 1/3

print(test_a/test_k)

from uuid import NAMESPACE_OID

#initial conditions
N = 3186989
I0 = 1/N
S0 = 1. - I0
R0 = 0.
x0 = [S0, I0, R0]

def wave1(a, k, wave):
  #declare a time vector (time window)
  size1 = wave.shape[0]
  t = np.linspace(0, size1-1, size1)
  #x = odeint(odes,x0,t, args=((1/2.5)+(0.01/2), (1/3)-0.01))

  #Experimental
  x = odeint(odes,x0,t, args=(a, k))

  S = x[:,0]
  I = x[:,1]
  R = x[:,2]

  y1_a = wave['Cumul. Infected for 7-day Avg'].to_numpy().copy()
  y1_a /= N
  y1_b = wave['Cumul. Infected for 28-day Avg'].to_numpy().copy()
  y1_b /= N
  y1_c = wave['Cumul. Infected'].to_numpy().copy()
  y1_c.astype(float)
  y1_c /= N
  y1 = np.array([y1_a, y1_b, y1_c])

  print("Max Infected peak: ", max(I))
  fig1 = plt.figure(1); fig1.clf()
  #plt.plot(t, S, 'g', lw=3, label='Suseptible')
  plt.plot(t, I, 'r', lw=3, label='Infective')
  #plt.plot(t, R, 'b', lw=3, label='Removed')
  # plt.plot(t, y1[0], 'y', lw=3, label='Total Infected for 7-day Avg')
  # plt.plot(t, y1[1], 'b', lw=3, label='Total Infected for 28-day Avg')
  # plt.plot(t, y2[2], 'black', lw=3, label='Total Infected')
  plt.scatter(t, y1[0], s=5, facecolors='none', edgecolors='y', label='Total Infected for 7-day Avg')
  plt.scatter(t, y1[1], s=5, facecolors='none', edgecolors='b', label='Total Infected for 28-day Avg')
  plt.scatter(t, y1[2], s=5, facecolors='none', edgecolors='black', label='Total Infected')
  plt.axis([0, 125, 0, 0.015])

  fig1.legend()
  plt.xlabel('Time (days)')
  plt.ylabel('Population')

  return S, I, R

const = 0.41
a = 0.5 * const
k = (1/4) * const

S, I, R = wave1(a, k, df_wave1)
R0 = a/k
print("a = ", a)
print("k = ", k)
print("Rate = ", 1/a)
print("Period = ", 1/k)
print("R0 = ", R0)
# print("S(120) = ", S[120])
# print("I(120) = ", I[120])

from uuid import NAMESPACE_OID

#initial conditions
#N = 3186989
N = 1000
I0 = 5/N
S0 = 1. - I0
R0 = 0.
x0 = [S0, I0, R0]

t = np.linspace(0, 10,100)
a, k = 6, 1.5
x = odeint(odes,x0,t, args=(a,k))

S = x[:,0]
I = x[:,1]
R = x[:,2]

fig1 = plt.figure(1); fig1.clf()
plt.plot(t, S, 'g', lw=3, label='Suseptible')
plt.plot(t, I, 'r', lw=3, label='Infective')
plt.plot(t, R, 'b', lw=3, label='Removed')


fig1.legend(loc=7)
plt.title('Figure 3: SIR Curve for a mini-pandemic')
plt.xlabel('Time (days)')
plt.ylabel('Population')

S

max(I)

S[-1]

kx = (a/k)*S[0]
y = k/a
1 - y*(1+np.log(x))

#initial conditions
N = 3186989
I0 = 1/N
S0 = 1. - I0
R0 = 0.
x0 = [S0, I0, R0]

def wave_infected(a, k, wave):
  #declare a time vector (time window)
  size1 = wave.shape[0]
  t = np.linspace(0, size1-1, size1)
  #x = odeint(odes,x0,t, args=((1/2.5)+(0.01/2), (1/3)-0.01))

  #Experimental
  x = odeint(odes,x0,t, args=(a, k))

  S = x[:,0]
  I = x[:,1]
  R = x[:,2]

  to_plot = wave['Number of Infected'].to_numpy().copy()
  to_plot /= N

  print("Max Infected peak: ", max(I))
  fig1 = plt.figure(1); fig1.clf()
  #plt.plot(t, S, 'g', lw=3, label='Suseptible')
  plt.plot(t, I, 'r', lw=3, label='Infective')
  #plt.plot(t, R, 'b', lw=3, label='Removed')
  # plt.plot(t, y1[0], 'y', lw=3, label='Total Infected for 7-day Avg')
  # plt.plot(t, y1[1], 'b', lw=3, label='Total Infected for 28-day Avg')
  # plt.plot(t, y2[2], 'black', lw=3, label='Total Infected')
  plt.scatter(t, to_plot, s=5, facecolors='none', edgecolors='y', label='Number of Infected')
  plt.axis([0, 125, 0, 0.015])

  fig1.legend()
  plt.xlabel('Time (days)')
  plt.ylabel('Population')

  return S, I, R

const = 1.9
a = (1/3.25) * const
k = (1/4) * const

S, I, R = wave_infected(a, k, df_wave1)
R0 = a/k
print("a = ", a)
print("k = ", k)
print("Rate = ", 1/a)
print("Period = ", 1/k)
print("R0 = ", R0)

df_wave2

const = 1.2
a, k = const * 1/4.2, const * 1/11
S, I, R = wave1(a, k, df_wave2)
R0 = a/k
print("a = ", a)
print("k = ", k)
print("Rate = ", 1/a)
print("k = ", 1/k)
print("R0 = ", R0)

"""# Wave 1, Wave 2, Wave 3, Wave 4 (Daily Cases)"""

from uuid import NAMESPACE_OID

#initial conditions
N = 3186989
I0 = 1/N
S0 = 1. - I0
R0 = 0.
x0 = [S0, I0, R0]

def daily_wave(a, k, wave):
  #declare a time vector (time window)
  size1 = wave.shape[0] + 120
  t = np.linspace(0, size1-1, size1)
  #x = odeint(odes,x0,t, args=((1/2.5)+(0.01/2), (1/3)-0.01))

  #Experimental
  x = odeint(odes,x0,t, args=(a, k))

  S = x[:,0]
  I = x[:,1]
  R = x[:,2]

  y1_a = wave['7-day Avg'].to_numpy().copy()
  y1_a /= N
  y1_a = list(y1_a)
  y1_a = [0.0 for i in range(60)] + y1_a + [0.0 for i in range(60)]

  y1_b = wave['28-day Avg'].to_numpy().copy()
  y1_b /= N
  y1_b = list(y1_b)
  y1_b = [0.0 for i in range(60)] + y1_b + [0.0 for i in range(60)]

  y1_c = wave['Infected per day'].to_numpy().copy()
  y1_c.astype(float)
  y1_c /= N
  y1_c = list(y1_c)
  y1_c = [0.0 for i in range(60)] + y1_c + [0.0 for i in range(60)]
  print(y1_c)

  y1 = np.array([y1_a, y1_b, y1_c])

  print("Max Infected peak: ", max(I))
  fig1 = plt.figure(1); fig1.clf()
  #plt.plot(t, S, 'g', lw=3, label='Suseptible')
  #plt.plot(t, I, 'r', lw=3, label='Infective')

  # I = list(I)
  # I = [0 for i in range(60)] + I + [0 for i in range(60)]
  # print(I)
  # t = list(t)
  # t = [(i+0.0) for i in range(60)] + [(60.0+i) for i in t] + [(i+183.0+60.0) for i in range(60)]

  print(t)
  plt.plot(t, I, 'r', lw=3, label='Infective')
  #plt.plot(t, R, 'b', lw=3, label='Removed')
  # plt.plot(t, y1[0], 'y', lw=3, label='Total Infected for 7-day Avg')
  # plt.plot(t, y1[1], 'b', lw=3, label='Total Infected for 28-day Avg')
  # plt.plot(t, y2[2], 'black', lw=3, label='Total Infected')
  plt.scatter(t, y1[0], s=5, facecolors='none', edgecolors='y', label='Total Infected for 7-day Avg')
  plt.scatter(t, y1[1], s=5, facecolors='none', edgecolors='b', label='Total Infected for 28-day Avg')
  plt.scatter(t, y1[2], s=5, facecolors='none', edgecolors='black', label='Total Infected')
  # plt.axis([0, 125, 0, 0.015])

  fig1.legend()
  plt.xlabel('Time (days)')
  plt.ylabel('Population')

  return S, I, R

a, k = 1/17, 1/21
print("Rate = ", 1/a)
print("Period = ", 1/k)
S, I, R = daily_wave(a, k, df_wave1)

a, k = 0.00001, 0.00001
print("Rate = ", 1/a)
print("Period = ", 1/k)
S, I, R = daily_wave(a, k, df_wave2)

a, k = 0.00001, 0.00001
print("Rate = ", 1/a)
print("Period = ", 1/k)
S, I, R = daily_wave(a, k, df_wave3)

#intersets at about t=124
N2 = int(S[126] * N)
N2

t = np.linspace(0, df_new.shape[0] - 1, df_new.shape[0])
to_plot = df_new['Number of Infected'].to_numpy().copy()
to_plot /= N
plt.plot(t, to_plot)

np.log(np.exp(2))
d = (1/120) * np.log(N*y1_a[120])
test_k = 1/3
test_a = test_k + d
print(test_a)
print(test_k)

#higher a-value means higher peak but shorter pandemic
#higher k-value means lower peak but longer pandemic

def wave2(a, k):
  size2 = df_wave2.shape[0]
  t = np.linspace(0, size2-1, size2)
  x = odeint(odes,x0,t, args=(a, k))

  S = x[:,0]
  I = x[:,1]
  R = x[:,2]

  y2_a = df_wave2['Total Infected for 7-day Avg'].to_numpy().copy()
  y2_a /= N2
  y2_b = df_wave2['Total Infected for 28-day Avg'].to_numpy().copy()
  y2_b /= N2
  y2_c = df_wave2['Total Infected'].to_numpy().copy()
  y2_c.astype(float)
  y2_c /= N2
  y2 = np.array([y2_a, y2_b, y2_c])

  fig2 = plt.figure(1); fig2.clf()
  #plt.plot(t, S, 'g', lw=3, label='Suseptible')
  plt.plot(t, I, 'r', lw=3, label='Infective')
  #plt.plot(t, R, 'b', lw=3, label='Removed')
  plt.plot(t, y2[0], 'y', lw=3, label='7-day Avg')
  plt.plot(t, y2[1], 'brown', lw=3, label='28-day Avg')
  plt.plot(t, y2[2], 'm', lw=3, label='Raw Data')

  fig2.legend()
  plt.xlabel('Time (days)')
  plt.ylabel('Population')

  return S, I, R

const = 0.35
a = 0.7*const
k = 0.3333333333333333*const
S, I, R = wave2(a, k)
R0 = a/k
print("a = ", a)
print("k = ", k)
print("R0 = ", R0)
print("Max = ", max(I))

d = (1/50) * np.log(N*y2_a[50])
test_k = 1/3
test_a = test_k + d
print(test_a)
print(test_k)

fig1 = plt.figure(1); fig1.clf()
#plt.plot(t, S, 'g', lw=3, label='Suseptible')
plt.plot(t, I, 'r', lw=3, label='Infective')
#plt.plot(t, R, 'b', lw=3, label='Removed')
plt.plot(t, y1[0], 'y', lw=3, label='7-day Avg')
plt.plot(t, y1[1], 'brown', lw=3, label='28-day Avg')
plt.plot(t, y1[2], 'm', lw=3, label='Raw Data')

fig1.legend()
plt.xlabel('Time (days)')
plt.ylabel('Population')

t = np.linspace(0, 10)
x = odeint(odes,x0,t, args=(6,1.4))

S = x[:,0]
I = x[:,1]
R = x[:,2]

print(max(I))
fig = plt.figure(1); fig.clf()
plt.plot(t, S, 'g', lw=3, label='Suseptible')
plt.plot(t, I, 'r', lw=3, label='Infective')
plt.plot(t, R, 'b', lw=3, label='Removed')

fig.legend()
plt.xlabel('Time (days)')
plt.ylabel('Population')

print(max(I))
print(max(y1[0]))